build(pre-push hook check):bypass husky hook through HUSKY=0

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -7,13 +7,26 @@ echo "\nPre Push Steps: (pre-push) : Git Guardian secrets detection"
 # load .env
 export $(cat .env | xargs)
 
-# check ggshield available
-if command_exists ggshield && test -t 1; then
-    ggshield -c .gitguardian.yaml scan path .  --recursive -y
-elif command_exists docker && test -t 1; then
-    docker run --rm -v $(pwd):/data \
-            -v $(pwd):/config \
-            -e GITGUARDIAN_API_KEY \
-            gitguardian/ggshield:latest \
-            ggshield -c /config/.gitguardian.yaml scan path .  --recursive -y
-fi
+# Commit sha with all zeros
+zero_commit="0000000000000000000000000000000000000000"
+
+while read -r oldrev newrev refname; do
+    # Check if a zero sha
+    if [ "${oldrev}" = "${zero_commit}" ]; then
+        # List everything reachable from newrev but not any heads
+        span="$(git for-each-ref --format='%(refname)' 'refs/heads/*' | sed 's/^/\^/') ${newrev}"
+    else
+        span="${oldrev}...${newrev}"
+    fi
+
+    if command_exists ggshield && test -t 1; then
+        ggshield scan commit-range "${span}" && continue
+    elif command_exists docker && test -t 1; then
+        docker run --rm -v $(pwd):/data ggshield -e GITGUARDIAN_API_KEY \
+            gitguardian/ggshield:latest ggshield scan commit-range "${span}" && continue
+    fi
+
+    echo "ERROR: Your push was rejected because it contained a policy break"
+    echo "ERROR: Please contact your Git administrator if this was a false positive."
+    exit 1
+done
